[fbthrift] Accommodate a new dependency on libaio
Summary:
facebook/fbthrift@ca7450fa2e4249750a710996bdd8dee6b0d97ebd adds a new
transitive dependency on libaio to fbthrift.  This broke my most recent
scheduled fbthrift build failed, where getdeps failed with:

    KeyError: 'project libaio has no fetcher configuration or system packages matching {distro=alma, distro_vers=10.0, fb=off, fbsource=off, os=linux, shared_libs=off, test=off}'

We can fix this by loosening the `rpms` specification in the libaio manifest,
so that it applies to AlmaLinux and not just CentOS Stream, and then ensuring
libaio-devel is installed in the fbthrift-builder image.

Test Plan:
scripts/build-fbthrift.sh